import { User, Job, ExchangeApplication, Conversation, Message, CreditRecord, SuccessCase } from '../types';

export const mockUsers: User[] = [
  {
    id: 'user-1',
    nickname: '张明远',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    role: 'seeker',
    city: '北京',
    industry: '互联网',
    workYears: 3,
    creditScore: 85,
    jobIntention: {
      position: '前端开发工程师',
      city: '北京',
      salaryRange: [25000, 35000],
    },
    resumeSummary: {
      education: '北京邮电大学 · 计算机科学与技术 · 本科',
      experience: ['字节跳动 · 前端开发 · 2年', '创业公司 · 全栈开发 · 1年'],
      skills: ['React', 'Vue', 'TypeScript', 'Node.js'],
    },
    isVerified: true,
    createdAt: Date.now() - 90 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'user-2',
    nickname: '李婉清',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    role: 'employee',
    city: '北京',
    industry: '互联网',
    workYears: 5,
    creditScore: 92,
    resumeSummary: {
      education: '清华大学 · 软件工程 · 硕士',
      experience: ['阿里巴巴 · 高级前端开发 · 3年'],
      skills: ['React', 'Node.js', '架构设计', '团队管理'],
    },
    isVerified: true,
    createdAt: Date.now() - 180 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'user-3',
    nickname: '王思琪',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
    role: 'seeker',
    city: '上海',
    industry: '金融',
    workYears: 4,
    creditScore: 78,
    jobIntention: {
      position: '产品经理',
      city: '上海',
      salaryRange: [30000, 45000],
    },
    resumeSummary: {
      education: '复旦大学 · 工商管理 · 硕士',
      experience: ['蚂蚁集团 · 产品经理 · 3年', '京东科技 · 产品专员 · 1年'],
      skills: ['产品设计', '数据分析', '项目管理', '用户研究'],
    },
    isVerified: true,
    createdAt: Date.now() - 60 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'user-4',
    nickname: '陈建国',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    role: 'employee',
    city: '北京',
    industry: '金融',
    workYears: 8,
    creditScore: 95,
    resumeSummary: {
      education: '北京大学 · 金融学 · 硕士',
      experience: ['中信证券 · 投行部VP · 5年', '高盛 · 分析员 · 3年'],
      skills: ['投行', '并购重组', '估值建模', '团队管理'],
    },
    isVerified: true,
    createdAt: Date.now() - 365 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'user-5',
    nickname: '刘雨薇',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&h=150&fit=crop',
    role: 'seeker',
    city: '深圳',
    industry: '制造业',
    workYears: 2,
    creditScore: 70,
    jobIntention: {
      position: 'UI设计师',
      city: '深圳',
      salaryRange: [15000, 25000],
    },
    resumeSummary: {
      education: '广州美术学院 · 视觉传达设计 · 本科',
      experience: ['设计工作室 · UI设计师 · 2年'],
      skills: ['Figma', 'Sketch', 'Adobe XD', '交互设计'],
    },
    isVerified: true,
    createdAt: Date.now() - 45 * 24 * 60 * 60 * 1000,
  },
];

export const mockJobs: Job[] = [
  {
    id: 'job-1',
    publisherId: 'user-2',
    publisherName: '李婉清',
    publisherAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    title: '高级前端开发工程师',
    company: '字节跳动',
    industry: '互联网',
    city: '北京',
    salaryRange: [35000, 55000],
    description: '负责抖音Web端的开发和优化，参与前端架构设计与技术选型。',
    requirements: ['5年以上前端开发经验', '精通React/Vue', '熟悉工程化', '有大型项目经验'],
    slots: 3,
    appliedCount: 1,
    status: 'open',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'job-2',
    publisherId: 'user-4',
    publisherName: '陈建国',
    publisherAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    title: '投资银行部项目经理',
    company: '中信证券',
    industry: '金融',
    city: '北京',
    salaryRange: [50000, 80000],
    description: '主导并购重组项目执行，负责客户关系维护与项目开发。',
    requirements: ['985/211硕士以上', '3年以上投行经验', '通过CPA/司法考试优先', '有完整项目经验'],
    slots: 2,
    appliedCount: 0,
    status: 'open',
    createdAt: Date.now() - 5 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'job-3',
    publisherId: 'user-2',
    publisherName: '李婉清',
    publisherAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    title: '前端架构师',
    company: '阿里巴巴',
    industry: '互联网',
    city: '杭州',
    salaryRange: [60000, 90000],
    description: '负责淘宝前端技术体系建设，推动技术革新与团队成长。',
    requirements: ['8年以上前端开发经验', '精通前端架构设计', '有大规模系统经验', '具备技术影响力'],
    slots: 1,
    appliedCount: 2,
    status: 'open',
    createdAt: Date.now() - 1 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'job-4',
    publisherId: 'user-4',
    publisherName: '陈建国',
    publisherAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    title: '风险管理分析师',
    company: '蚂蚁集团',
    industry: '金融',
    city: '杭州',
    salaryRange: [40000, 60000],
    description: '建立风险评估模型，监控信贷业务风险指标。',
    requirements: ['金融/统计相关专业', '3年以上风控经验', '熟练使用Python/SQL', '有建模经验'],
    slots: 4,
    appliedCount: 1,
    status: 'open',
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'job-5',
    publisherId: 'user-2',
    publisherName: '李婉清',
    publisherAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    title: '资深UI设计师',
    company: '腾讯',
    industry: '互联网',
    city: '深圳',
    salaryRange: [28000, 42000],
    description: '负责微信支付相关产品设计，打造极致的用户体验。',
    requirements: ['4年以上UI设计经验', '精通Figma/Sketch', '有金融产品经验优先', '具备设计系统经验'],
    slots: 2,
    appliedCount: 0,
    status: 'open',
    createdAt: Date.now() - 4 * 24 * 60 * 60 * 1000,
  },
];

export const mockApplications: ExchangeApplication[] = [
  {
    id: 'app-1',
    jobId: 'job-1',
    publisherId: 'user-2',
    jobTitle: '高级前端开发工程师',
    company: '字节跳动',
    seekerId: 'user-1',
    seekerName: '张明远',
    seekerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    resumeSummary: '3年前端经验，熟练使用React和TypeScript，参与过多个大型项目',
    status: 'accepted',
    feedbackDeadline: Date.now() + 7 * 24 * 60 * 60 * 1000,
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'app-2',
    jobId: 'job-3',
    publisherId: 'user-2',
    jobTitle: '前端架构师',
    company: '阿里巴巴',
    seekerId: 'user-1',
    seekerName: '张明远',
    seekerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
    resumeSummary: '熟悉前端工程化，有架构设计经验，期望进一步发展',
    status: 'pending',
    createdAt: Date.now() - 12 * 60 * 60 * 1000,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    participantId: 'user-2',
    participantName: '李婉清',
    participantAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
    lastMessage: '你的简历已收到，我会尽快内推',
    lastMessageTime: Date.now() - 2 * 60 * 60 * 1000,
    unreadCount: 0,
  },
  {
    id: 'conv-2',
    participantId: 'user-4',
    participantName: '陈建国',
    participantAvatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop',
    lastMessage: '下周一会安排面试，请保持手机畅通',
    lastMessageTime: Date.now() - 24 * 60 * 60 * 1000,
    unreadCount: 1,
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    senderId: 'user-1',
    content: '您好，我看到您发布了字节跳动的前端岗位，请问还开放吗？',
    type: 'text',
    createdAt: Date.now() - 3 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    senderId: 'user-2',
    content: '您好，还在开放的。我看了一下您的简历，非常匹配我们团队的需求。',
    type: 'text',
    createdAt: Date.now() - 2.5 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    senderId: 'user-1',
    content: '太好了！请问什么时候可以安排面试呢？',
    type: 'text',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'msg-4',
    conversationId: 'conv-1',
    senderId: 'user-2',
    content: '请约定反馈时间',
    type: 'feedback_约定',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'msg-5',
    conversationId: 'conv-1',
    senderId: 'user-1',
    content: '好的，我这周内都可以，请问下周三下午方便吗？',
    type: 'text',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000 + 30 * 60 * 1000,
  },
  {
    id: 'msg-6',
    conversationId: 'conv-1',
    senderId: 'user-2',
    content: '好的，就定下周三下午3点。我这边会安排技术面试，面试官是我们团队的技术负责人。',
    type: 'text',
    createdAt: Date.now() - 2 * 24 * 60 * 60 * 1000 + 60 * 60 * 1000,
  },
  {
    id: 'msg-7',
    conversationId: 'conv-1',
    senderId: 'user-2',
    content: '你的简历已收到，我会尽快内推',
    type: 'text',
    createdAt: Date.now() - 2 * 60 * 60 * 1000,
  },
  {
    id: 'msg-8',
    conversationId: 'conv-2',
    senderId: 'user-4',
    content: '下周一会安排面试，请保持手机畅通',
    type: 'text',
    createdAt: Date.now() - 24 * 60 * 60 * 1000,
  },
];

export const mockCreditRecords: CreditRecord[] = [
  {
    id: 'cr-1',
    userId: 'user-1',
    type: 'success',
    score: 10,
    reason: '内推成功入职',
    relatedUserId: 'user-2',
    relatedUserName: '李婉清',
    createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'cr-2',
    userId: 'user-1',
    type: 'onTimeFeedback',
    score: 5,
    reason: '按时提交反馈',
    createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
  },
  {
    id: 'cr-3',
    userId: 'user-1',
    type: 'success',
    score: 10,
    reason: '再次内推成功',
    relatedUserId: 'user-4',
    relatedUserName: '陈建国',
    createdAt: Date.now() - 10 * 24 * 60 * 60 * 1000,
  },
];

export const mockSuccessCases: SuccessCase[] = [
  {
    id: 'sc-1',
    seekerPosition: '前端开发工程师',
    seekerIndustry: '互联网',
    companyIndustry: '电商',
    matchScore: 92,
    hiredPeriod: '15天',
    successRate: 85,
  },
  {
    id: 'sc-2',
    seekerPosition: '产品经理',
    seekerIndustry: '金融科技',
    companyIndustry: '消费金融',
    matchScore: 88,
    hiredPeriod: '20天',
    successRate: 78,
  },
  {
    id: 'sc-3',
    seekerPosition: 'UI设计师',
    seekerIndustry: '移动互联网',
    companyIndustry: '社交',
    matchScore: 90,
    hiredPeriod: '12天',
    successRate: 90,
  },
];

export const industries = [
  '互联网',
  '金融',
  '制造业',
  '医疗健康',
  '教育培训',
  '房地产',
  '零售',
  '物流',
];

export const cities = [
  '北京',
  '上海',
  '深圳',
  '广州',
  '杭州',
  '成都',
  '南京',
  '武汉',
];

export const salaryRanges = [
  { label: '10k-20k', range: [10000, 20000] as [number, number] },
  { label: '20k-35k', range: [20000, 35000] as [number, number] },
  { label: '35k-50k', range: [35000, 50000] as [number, number] },
  { label: '50k-80k', range: [50000, 80000] as [number, number] },
  { label: '80k以上', range: [80000, 200000] as [number, number] },
];
